name: 'Dastardly Scan Action'
description: 'Runs a Dastardly scan against a target site'
author: 'PortSwigger'
inputs:
  target-url: 
    description: https://www.dsw.com/
    required: true
  output-filename:
    description: dswcom
    required: false
    default: dastardly-report.xml
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    BURP_START_URL: ${{ inputs.target-url }}
    BURP_REPORT_FILE_PATH: /github/workspace/${{ inputs.output-filename }}
branding:
  icon: 'activity'
  color: 'green'
